name: 'OpenAPI Spec: changelog'
description: 'Generate a changelog for OpenAPI Specification 3'
inputs:
  base:
    description: 'Path of original OpenAPI spec in YAML or JSON format'
    required: true
  revision:
    description: 'Path of revised OpenAPI spec in YAML or JSON format'
    required: true
  include-path-params:
    description: 'Include path parameter names in endpoint matching'
    required: false
    default: 'false'
  exclude-elements:
    description: 'Exclude certain kinds of changes'
    required: false
    default: ''
  composed:
    description: 'Run in composed mode'
    required: false
    default: 'false'
  output-to-file:
    description: 'Output to a file at the given path'
    required: false
    default: ''
outputs:
  changelog:
    description: 'Output summary of API changelog'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.revision }}
    - ${{ inputs.include-path-params }}
    - ${{ inputs.exclude-elements }}
    - ${{ inputs.composed }}
    - ${{ inputs.output-to-file }}
