name: 'OpenAPI Spec: changelog'
description: 'Generate a changelog for OpenAPI Specification 3'
inputs:
  base:
    description: 'Path of original OpenAPI spec in YAML or JSON format'
    required: true
  revision:
    description: 'Path of revised OpenAPI spec in YAML or JSON format'
    required: true
  include-path-params:
    description: 'Include path parameter names in endpoint matching'
    required: false
    default: 'false'
outputs:
  changelog:
    description: 'Details of all changes in the OpenAPI spec, "info", "warn" and "error"'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.revision }}
    - ${{ inputs.include-path-params }}
