name: 'OpenAPI Spec: diff'
description: 'Generate a diff report for OpenAPI Specification 3'
inputs:
  base:
    description: 'Path of original OpenAPI spec in YAML or JSON format'
    required: true
  revision:
    description: 'Path of revised OpenAPI spec in YAML or JSON format'
    required: true
  format:
    description: 'Output format'
    required: false
    default: 'yaml'
  fail-on-diff:
    description: 'Fail with exit code 1 if a difference is found'
    required: false
    default: 'false'
  include-path-params:
    description: 'Include path parameter names in endpoint matching'
    required: false
    default: 'false'
  exclude-elements:
    description: 'Exclude certain kinds of changes'
    required: false
    default: ''
  composed:
    description: 'Run in composed mode'
    required: false
    default: 'false'
outputs:
  diff:
    description: 'Output summary of API diff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.revision }}
    - ${{ inputs.format }}
    - ${{ inputs.fail-on-diff }}
    - ${{ inputs.include-path-params }}
    - ${{ inputs.exclude-elements }}
    - ${{ inputs.composed }}
