name: 'OpenAPI Spec: diff'
description: 'A diff tool for OpenAPI Specification 3'
inputs:
  base:
    description: 'Path of original OpenAPI spec in YAML or JSON format'
    required: true
  revision:
    description: 'Path of revised OpenAPI spec in YAML or JSON format'
    required: true
  format:
    description: 'Output format'
    required: false
    default: 'yaml'
  fail-on-diff:
    description: 'Fail with exit code 1 if a difference is found'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.revision }}
    - ${{ inputs.format }}
    - ${{ inputs.fail-on-diff }}
