openapi: "3.0.0"
info:
  version: 1.0.0
  title: Petstore allOf
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    BaseEntity:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
    PetFields:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
    Pet:
      allOf:
        - $ref: "#/components/schemas/BaseEntity"
        - $ref: "#/components/schemas/PetFields"
